### ISSUE TITLE
When a user refresh the page he is logged out

### ISSUE THREAD

**Issue by bolmsten** [SciCatProject/scicat-backend-next#71]

**Comment by henrikjohansson712** [comment]
# Reason for issue

After logging in, the JWT is stored as a cookie in the client. The JWT has the format "Bearer xxx", which, when stored as a cookie is encoded as "Bearer%20xxx". This causes the backend to not recognize the token as a valid JWT when the JWT is fetched from the cookie for subsequent requests.


# Solution

Wrap cookie getter in the fronted in a `decodeURIComponent()` function.

# Fixed

Fixed with frontend commit [c7aeec5](https://github.com/SciCatProject/frontend/commit/c7aeec5fb1f795f1752934729aa7aeed55b147a7).
