### ISSUE TITLE
Jwt token returned from logging in is different (less information than jwt token returned from /users/jwt)

### ISSUE THREAD

**Issue by nguyenlinhlinh** [SciCatProject/scicat-backend-next#74]
## Issue Name
Jwt token returned from logging in is different (less information) than jwt token returned from `/users/jwt`
### Summary
On succeed authentication the backend send back response with access token.  This access token has is longer and has more information about the user than the one returned by /user/jwt endpoint. 
### Steps to Reproduce
- Log in and save the access token
- Use the saved access token to fetch jwt token by sending a request to /users/jwt
- Decode and compare the to tokens on [jwt.io](jwt.io)
### Example of the two tokens
Token1 `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjgxZmUwZTRjN2Y2ZjJlNDdiOGM5MmUiLCJ1c2VybmFtZSI6ImluZ2VzdG9yIiwiZW1haWwiOiJzY2ljYXRpbmdlc3RvckB5b3VyLnNpdGUiLCJfX3YiOjAsImlhdCI6MTY1MjY5OTMwOSwiZXhwIjoxNjUyNzAyOTA5fQ.lMihGDqUvh1ey-RJZbxTPm7vaBOJS0CRhPSQkpOAlXA`
Token2
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjYyODFmZTBlNGM3ZjZmMmU0N2I4YzkyZSIsImdyb3VwcyI6WyJpbmdlc3RvciIsImdsb2JhbGFjY2VzcyJdLCJpYXQiOjE2NTI2OTkzMjgsImV4cCI6MTY1MjcwMjkyOH0.TolPCE9ESHZHw1bUOoBZhYwmC-27EoXG_teA1uExTd4`
### Current Behaviour
The two tokens for the same user have different information.
### Expected Behaviour
The two tokens should contain the same information

**Comment by henrikjohansson712** [comment]
The two tokens have different purposes. In the old backend we have the endpoint `/users/jwt`, that is used for authentication against the [Zip-Service](https://github.com/SciCatProject/zip-service). It is not related to the token used authentication against SciCat. Now that we're using JWT for authentication against this new backend implementation, I understand that it's confusing for users to have this endpoint. Especially since it doesn't come with any explanation of its purpose.

In this new implementation of the backend there is really no need to keep the `/users/jwt` endpoint, as we can store the same information in the SciCat authentication JWT and just forward that to the Zip-Service. Right now, however, it's necessary to keep the endpoint because the field names in the two JWTs are incompatible with each other and it would also require some refactoring both in the SciCat Frontend and in the Zip-Service to make it work. Going through with this refactoring would, in turn, break the compatibility between these two services and the old backend, so right now it's not an option.

**Comment by nguyenlinhlinh** [comment]
I see, thank for the clarification.
